version: '3.8'

services:
  client:
    container_name: issue_tracker_frontend
    build:
      context: ./
      args:
        - EXPOSED_PORT=${FRONTEND_INTERNAL_HTTP_PORT}
    volumes:
      - .:/app
      - exclude:/app/node_modules/
    ports:
      - '${FRONTEND_EXPOSED_HTTP_PORT}:${FRONTEND_INTERNAL_HTTP_PORT}'
volumes:
  exclude:
